# Placeholder messages support MiniMessage formatting.
# https://docs.advntr.dev/minimessage/format.html
placeholders:
  canvote:
    available: "<green>Vote available!</green>"
    unavailable: "<gray>Thanks for voting!</gray>"
