name: AshTemplate
version: '${project.version}'
main: me.neoblade298.ashtemplate.AshTemplate
api-version: '1.21'
depend: [NeoCore]
commands:
  at:
    description: AshTemplate base command
    permission: ashtemplate.general
