name: AshVote
version: '${project.version}'
main: me.neoblade298.ashvote.AshVote
api-version: '1.21'
depend: [NeoCore]
softdepend: [Votifier]
commands:
  vote:
    description: AshVote base command
    permission: ashvote.vote
  voteadmin:
    description: AshVote admin command
    permission: ashvote.admin
permissions:
  ashvote.vote:
    description: Access to vote links, personal stats, and leaderboards
    default: true
  ashvote.admin:
    description: Access to all AshVote administrative commands
    default: op
